# Using a lightweight Node.js image
FROM node:20-alpine AS base

# Setting Up Working Directory
WORKDIR /usr/src/vendo-backend

# Copy package.json and pnpm-lock.yaml first to take advantage of Docker cache
COPY package*.json pnpm-lock.yaml ./

# Install pnpm globally
RUN npm install -g pnpm

# Install only development dependencies
RUN pnpm install

# Expose the application port (8080)
EXPOSE 8080

# Start application
CMD ["pnpm", "dev"]