export enum ERROR_CODES {
  TOO_MANY_REQUESTS = 'TOO_MANY_REQUESTS',
  GENERAL_ERROR = 'GENERAL_ERROR',
  INVALID_JSON_CONFIG = 'INVALID_JSON_CONFIG',
  ROUTE_NOT_FOUND = 'ROUTE_NOT_FOUND',
  UNAUTHORIZED = 'UNAUTHORIZED',
  NOT_FOUND = 'NOT_FOUND',
  PAYMENT_REQUIRED = 'PAYMENT_REQUIRED',
  FORBIDDEN = 'FORBIDDEN',
  METHOD_NOT_ALLOWED = 'METHOD_NOT_ALLOWED',
  CONFLICT = 'CONFLICT',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',

  AUTH_EMAIL_ALREADY_EXISTS = 'AUTH_EMAIL_ALREADY_EXISTS',
  AUTH_INVALID_CREDENTIALS = 'AUTH_INVALID_CREDENTIALS',

  EMAIL_SENDING_FAILED = 'EMAIL_SENDING_FAILED',
}

export type TErrorCodes = keyof typeof ERROR_CODES;
