export enum ERROR_CODES {
  TOO_MANY_REQUESTS = 'TOO_MANY_REQUESTS',
  GENERAL_ERROR = 'GENERAL_ERROR',
  INVALID_JSON_CONFIG = 'INVALID_JSON_CONFIG',
  ROUTE_NOT_FOUND = 'ROUTE_NOT_FOUND',
  UNAUTHORIZED = 'UNAUTHORIZED',
  NOT_FOUND = 'NOT_FOUND',
  PAYMENT_REQUIRED = 'PAYMENT_REQUIRED',
  FORBIDDEN = 'FORBIDDEN',
  METHOD_NOT_ALLOWED = 'METHOD_NOT_ALLOWED',
  CONFLICT = 'CONFLICT',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',

  AUTH_EMAIL_ALREADY_EXISTS = 'AUTH_EMAIL_ALREADY_EXISTS',
  AUTH_INVALID_CREDENTIALS = 'AUTH_INVALID_CREDENTIALS',
  AUTH_REFRESH_TOKEN_NOT_PROVIDED = 'AUTH_REFRESH_TOKEN_NOT_PROVIDED',
  AUTH_REFRESH_TOKEN_INVALID = 'AUTH_REFRESH_TOKEN_INVALID',
  AUTH_SESSION_NOT_FOUND = 'AUTH_SESSION_NOT_FOUND',
  AUTH_SESSION_EXPIRED = 'AUTH_SESSION_EXPIRED',
  AUTH_PASSWORD_SAME = 'AUTH_PASSWORD_SAME',

  EMAIL_SENDING_FAILED = 'EMAIL_SENDING_FAILED',

  VERIFICATION_CODE_INVALID_OR_EXPIRED = 'VERIFICATION_CODE_INVALID_OR_EXPIRED',
  UNABLE_TO_VERIFY_EMAIL = 'UNABLE_TO_VERIFY_EMAIL',

  USER_NOT_FOUND = 'USER_NOT_FOUND',
}

export type TErrorCodes = keyof typeof ERROR_CODES;
